SELECT * FROM APP_ADMIN.INVENTORY_OVERVIEW;
SELECT * FROM APP_ADMIN.SUPPLIER_PRODUCTS;
SELECT * FROM APP_ADMIN.LOW_STOCK_ALERT;
SELECT * FROM APP_ADMIN.SUPPLIER_PERFORMANCE ;
SELECT * FROM APP_ADMIN.CATEGORY_PERFORMANCE;
 