SELECT * FROM APP_ADMIN.CUSTOMER_PURCHASE_HISTORY;
SELECT * FROM APP_ADMIN.TOP_SELLING_PRODUCTS;
SELECT * FROM APP_ADMIN.LOYALTY_PROGRAM_PARTICIPATION;
SELECT * FROM APP_ADMIN.SALES_TRENDS;
SELECT * FROM APP_ADMIN.LATEST_CUSTOMER_INVOICE;
SELECT * FROM APP_ADMIN.SEASONAL_SALES_TRENDS;
SELECT * FROM APP_ADMIN.CUSTOMER_LIFETIME_VALUE;